version: "3"
services:
  py-dev-environment:
    build: .
    volumes:
      - ./src:/app
    ports:
      # ここで公開ポート設定する
      - "8080:8080"
    networks:
      - py-default
    
networks:
  py-default:
    driver: bridge
    external:
      true
