version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: task
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    restart: always
    networks:
      - mysql-network

  cli:
    image: mysql:latest
    networks:
      - mysql-network
    command: mysql -hmysql -uuser -ppassword db

networks:
  mysql-network:
    driver: bridge