run:
	DB_HOST=127.0.0.1
	DB_PORT=3306
	DB_USER=mysql
	DB_PASS=mysql
	DB_NAME=task
	C:/Users/murasame/anaconda3/python.exe c:/Users/murasame/Desktop/spring-hal/py24/task/01/main.py

mysql:
	docker-compose up -d
.PHONY: run mysql