version: "3"
services:
  python-develop-environment:
    build: .
    volumes:
      - ./src:/app
    ports:
      # ここで公開ポート設定する
      - "8080:8080"
    environment:
      - TZ=Asia/Tokyo
      # ここで環境変数設定する
      - COMPUTER_VISION_SUBSCRIPTION_KEY=
      - COMPUTER_VISION_REGION=japaneast
      - IMAGE_PATH=