version: "3"
services:
  python-develop-environment:
    build: .
    volumes:
      - ./src:/app
    ports:
      # ここで公開ポート設定する
      - "8080:8080"
    networks:
      - py-default
    environment:
      - PORT:8080
      - HOST:0.0.0.0
  
networks:
  py-default:
    driver: bridge
    external:
      true
